service: power-of
frameworkVersion: '3'

provider:
  name: aws
  stage: test
  runtime: python3.8
  memorySize: 128
  timeout: 10
  deploymentBucket:
    name: fal-demo-functions-packages
    serverSideEncryption: AES256

plugins:
  - serverless-deployment-bucket

functions:
  handler:
    handler: handler.power_of
