service: notify-email
frameworkVersion: '2'

provider:
  name: aws
  stage: test
  runtime: go1.x
  lambdaHashingVersion: 20201221

package:
  exclude:
    - '*/**'
  include:
    - bin/**

functions:
  handler:
    handler: bin/handler
