service: extract-data
frameworkVersion: '2'

provider:
  name: aws
  stage: test
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 128
  timeout: 10
  deploymentBucket:
    name: fal-demo-functions-packages
    serverSideEncryption: AES256

plugins:
  - serverless-deployment-bucket

package:
  exclude:
    - '*/**'
  include:
    - handler.js
    - scraper/**
    - node_modules/**

functions:
  handler:
    handler: handler.extractData
