service: extract-data
frameworkVersion: '2'

provider:
  name: aws
  stage: test
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

package:
  exclude:
    - '*/**'
  include:
    - handler.js
    - scraper/**
    - node_modules/**

functions:
  handler:
    handler: handler.extractData
