service: plus-one
frameworkVersion: '2'

provider:
  name: aws
  stage: test
  runtime: java11
  lambdaHashingVersion: 20201221

package:
  artifact: build/distributions/plusone.zip

functions:
  handler:
    handler: com.plusone.Handler
