service: plus-one
frameworkVersion: '3'

provider:
  name: aws
  stage: test
  runtime: java11
  memorySize: 128
  timeout: 10
  deploymentBucket:
    name: fal-demo-functions-packages
    serverSideEncryption: AES256

plugins:
  - serverless-deployment-bucket

package:
  artifact: build/distributions/plusone.zip

functions:
  handler:
    handler: com.plusone.Handler
