name: Build test

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.x

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.x

      - name: Install C and C++ header files
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib
        if: matrix.os == 'ubuntu-latest'

      - name: Install Conan and package tools
        run: |
          python3 -m pip install --upgrade pip
          pip3 install conan
          pip3 install conan_package_tools

      - name: Configure Conan
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
        if: matrix.os == 'ubuntu-latest'

      - name: Build FAL
        run: |
          make init
          make build

      - name: Install wrappers dependencies
        run: |
          ( cd fal/wrappers/javascript && npm install )
          ( cd fal/wrappers/ruby && bundle install )

      - name: Run tests
        run: make tests
