name: Build test

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

        include:
          - os: ubuntu-latest
            python-arch: 'x64'
            python-version: '3.8.x'
            prepare-python: true
            install-headerfiles: true
            configure-conan: true

          - os: macos-latest
            python-arch: 'x64'
            python-version: '3.8.x'
            prepare-python: true
            install-headerfiles: false
            configure-conan: false

          - os: windows-latest
            python-arch: 'x64'
            python-version: '3.8.x'
            prepare-python: true
            install-headerfiles: false
            configure-conan: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.python-arch }}
        if: matrix.prepare-python

      - name: Install C and C++ header files
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib g++-multilib
        if: matrix.install-headerfiles

      - name: Install conan && conan package tools
        run: |
          python3 -m pip install --upgrade pip
          pip3 install conan
          pip3 install conan_package_tools

      - name: Configure conan
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
        if: matrix.configure-conan

      - name: Build
        run: |
          make init
          make build
        env:
          CONAN_PIP_COMMAND: pip3

      - name: Run test
        run: python3 tests/python/main.py
